
domain(blocks).

sequence_task(30, [grip_from_blocks(block7, tom, block1), put_on_blocks(block7, tom, block6), grip_from_one_block(block1, tom, block2), put_on_blocks(block1, tom, block7), grip_from_table(block2, tom), put_on_blocks(block2, tom, block1)], _, _).

sequence_task(29, [grip_from_one_block(block6, tom, block5), put_on_table(block6, tom), grip_from_table(block5, tom), put_on_one_block(block5, tom, block6), grip_from_table(block1, tom), put_on_blocks(block1, tom, block4), grip_from_one_block(block7, tom, block3), put_on_blocks(block7, tom, block5), grip_from_blocks(block1, tom, block4), put_on_table(block1, tom), grip_from_table(block3, tom), put_on_one_block(block3, tom, block1), grip_from_blocks(block7, tom, block5), put_on_blocks(block7, tom, block4), grip_from_one_block(block3, tom, block1), put_on_blocks(block3, tom, block5), grip_from_table(block1, tom), put_on_blocks(block1, tom, block3), grip_from_blocks(block7, tom, block4), put_on_table(block7, tom), grip_from_blocks(block1, tom, block3), put_on_blocks(block1, tom, block4), grip_from_blocks(block3, tom, block5), put_on_table(block3, tom), grip_from_one_block(block5, tom, block6), put_on_blocks(block5, tom, block1), grip_from_table(block6, tom), put_on_one_block(block6, tom, block3), grip_from_table(block7, tom), put_on_blocks(block7, tom, block6)], _, _).

sequence_task(28, [grip_from_table(block3, tom), put_on_blocks(block3, tom, block7), grip_from_one_block(block5, tom, block1), put_on_blocks(block5, tom, block6), grip_from_blocks(block3, tom, block7), put_on_one_block(block3, tom, block1), grip_from_one_block(block7, tom, block4), put_on_blocks(block7, tom, block3), grip_from_blocks(block5, tom, block6), put_on_blocks(block5, tom, block7), grip_from_one_block(block6, tom, block2), put_on_one_block(block6, tom, block4), grip_from_blocks(block5, tom, block7), put_on_blocks(block5, tom, block6), grip_from_blocks(block7, tom, block3), put_on_blocks(block7, tom, block5), grip_from_one_block(block3, tom, block1), put_on_table(block3, tom), grip_from_table(block1, tom), put_on_blocks(block1, tom, block7), grip_from_table(block3, tom), put_on_one_block(block3, tom, block2), grip_from_blocks(block1, tom, block7), put_on_blocks(block1, tom, block3), grip_from_blocks(block7, tom, block5), put_on_table(block7, tom), grip_from_blocks(block5, tom, block6), put_on_blocks(block5, tom, block1), grip_from_table(block7, tom), put_on_blocks(block7, tom, block5)], _, _).

sequence_task(27, [grip_from_blocks(block5, tom, block2), put_on_one_block(block5, tom, block1), grip_from_blocks(block2, tom, block4), put_on_table(block2, tom), grip_from_blocks(block4, tom, block6), put_on_blocks(block4, tom, block5), grip_from_table(block2, tom), put_on_blocks(block2, tom, block6), grip_from_blocks(block4, tom, block5), put_on_blocks(block4, tom, block2), grip_from_one_block(block5, tom, block1), put_on_table(block5, tom), grip_from_blocks(block4, tom, block2), put_on_one_block(block4, tom, block5), grip_from_table(block1, tom), put_on_blocks(block1, tom, block2), grip_from_one_block(block4, tom, block5), put_on_blocks(block4, tom, block1), grip_from_table(block5, tom), put_on_blocks(block5, tom, block4)], _, _).

sequence_task(26, [grip_from_blocks(block6, tom, block5), put_on_one_block(block6, tom, block7), grip_from_one_block(block5, tom, block4), put_on_blocks(block5, tom, block6), grip_from_blocks(block1, tom, block2), put_on_table(block1, tom), grip_from_one_block(block2, tom, block3), put_on_blocks(block2, tom, block5), grip_from_table(block3, tom), put_on_one_block(block3, tom, block1), grip_from_table(block4, tom), put_on_blocks(block4, tom, block3), grip_from_blocks(block2, tom, block5), put_on_table(block2, tom), grip_from_blocks(block4, tom, block3), put_on_blocks(block4, tom, block5), grip_from_table(block2, tom), put_on_blocks(block2, tom, block3), grip_from_blocks(block4, tom, block5), put_on_blocks(block4, tom, block2), grip_from_blocks(block5, tom, block6), put_on_blocks(block5, tom, block4), grip_from_one_block(block6, tom, block7), put_on_table(block6, tom), grip_from_blocks(block5, tom, block4), put_on_table(block5, tom), grip_from_table(block6, tom), put_on_blocks(block6, tom, block4), grip_from_table(block5, tom), put_on_one_block(block5, tom, block7)], _, _).

sequence_task(25, [grip_from_blocks(block1, tom, block7), put_on_blocks(block1, tom, block5), grip_from_one_block(block2, tom, block6), put_on_blocks(block2, tom, block7), grip_from_blocks(block1, tom, block5), put_on_one_block(block1, tom, block6), grip_from_one_block(block5, tom, block3), put_on_blocks(block5, tom, block1), grip_from_table(block3, tom), put_on_blocks(block3, tom, block2), grip_from_blocks(block5, tom, block1), put_on_blocks(block5, tom, block3), grip_from_one_block(block1, tom, block6), put_on_table(block1, tom), grip_from_blocks(block5, tom, block3), put_on_one_block(block5, tom, block6), grip_from_table(block1, tom), put_on_blocks(block1, tom, block5), grip_from_blocks(block3, tom, block2), put_on_table(block3, tom), grip_from_blocks(block2, tom, block7), put_on_blocks(block2, tom, block1), grip_from_table(block3, tom), put_on_blocks(block3, tom, block2), grip_from_one_block(block7, tom, block4), put_on_table(block7, tom), grip_from_table(block4, tom), put_on_one_block(block4, tom, block7), grip_from_blocks(block3, tom, block2), put_on_blocks(block3, tom, block4)], _, _).

sequence_task(24, [grip_from_one_block(block7, tom, block4), put_on_one_block(block7, tom, block2), grip_from_one_block(block3, tom, block1), put_on_blocks(block3, tom, block5), grip_from_one_block(block7, tom, block2), put_on_one_block(block7, tom, block1), grip_from_table(block2, tom), put_on_one_block(block2, tom, block4), grip_from_blocks(block3, tom, block5), put_on_blocks(block3, tom, block7), grip_from_one_block(block5, tom, block6), put_on_table(block5, tom), grip_from_one_block(block2, tom, block4), put_on_one_block(block2, tom, block5), grip_from_table(block6, tom), put_on_blocks(block6, tom, block2), grip_from_blocks(block3, tom, block7), put_on_one_block(block3, tom, block4), grip_from_one_block(block7, tom, block1), put_on_table(block7, tom), grip_from_table(block1, tom), put_on_blocks(block1, tom, block3), grip_from_blocks(block6, tom, block2), put_on_table(block6, tom), grip_from_table(block7, tom), put_on_blocks(block7, tom, block2), grip_from_table(block6, tom), put_on_blocks(block6, tom, block7), grip_from_blocks(block1, tom, block3), put_on_table(block1, tom)], _, _).

sequence_task(23, [grip_from_one_block(block1, tom, block6), put_on_blocks(block1, tom, block4), grip_from_table(block6, tom), put_on_blocks(block6, tom, block1)], _, _).

sequence_task(22, [grip_from_blocks(block6, tom, block7), put_on_table(block6, tom), grip_from_blocks(block1, tom, block2), put_on_one_block(block1, tom, block6), grip_from_one_block(block7, tom, block3), put_on_blocks(block7, tom, block2), grip_from_table(block3, tom), put_on_blocks(block3, tom, block1), grip_from_blocks(block7, tom, block2), put_on_blocks(block7, tom, block3), grip_from_blocks(block2, tom, block5), put_on_table(block2, tom), grip_from_one_block(block5, tom, block4), put_on_one_block(block5, tom, block2), grip_from_blocks(block7, tom, block3), put_on_one_block(block7, tom, block4), grip_from_one_block(block5, tom, block2), put_on_blocks(block5, tom, block3), grip_from_table(block2, tom), put_on_blocks(block2, tom, block5), grip_from_one_block(block7, tom, block4), put_on_blocks(block7, tom, block2), grip_from_table(block4, tom), put_on_blocks(block4, tom, block7)], _, _).

sequence_task(21, [grip_from_blocks(block7, tom, block5), put_on_blocks(block7, tom, block1), grip_from_one_block(block5, tom, block6), put_on_blocks(block5, tom, block7), grip_from_one_block(block3, tom, block4), put_on_blocks(block3, tom, block5), grip_from_table(block6, tom), put_on_one_block(block6, tom, block4), grip_from_blocks(block3, tom, block5), put_on_blocks(block3, tom, block6), grip_from_blocks(block5, tom, block7), put_on_table(block5, tom), grip_from_blocks(block7, tom, block1), put_on_table(block7, tom), grip_from_table(block5, tom), put_on_one_block(block5, tom, block7), grip_from_blocks(block3, tom, block6), put_on_blocks(block3, tom, block5), grip_from_one_block(block1, tom, block2), put_on_blocks(block1, tom, block6), grip_from_table(block2, tom), put_on_blocks(block2, tom, block1), grip_from_blocks(block3, tom, block5), put_on_table(block3, tom), grip_from_blocks(block2, tom, block1), put_on_one_block(block2, tom, block3), grip_from_one_block(block5, tom, block7), put_on_table(block5, tom), grip_from_table(block7, tom), put_on_blocks(block7, tom, block1)], _, _).

sequence_task(20, [grip_from_table(block6, tom), put_on_blocks(block6, tom, block2)], _, _).

sequence_task(19, [grip_from_blocks(block2, tom, block7), put_on_one_block(block2, tom, block1), grip_from_one_block(block7, tom, block6), put_on_blocks(block7, tom, block2), grip_from_blocks(block3, tom, block5), put_on_one_block(block3, tom, block6), grip_from_blocks(block7, tom, block2), put_on_table(block7, tom), grip_from_one_block(block3, tom, block6), put_on_table(block3, tom), grip_from_table(block7, tom), put_on_one_block(block7, tom, block6), grip_from_one_block(block2, tom, block1), put_on_blocks(block2, tom, block7), grip_from_table(block1, tom), put_on_one_block(block1, tom, block3), grip_from_one_block(block5, tom, block4), put_on_table(block5, tom), grip_from_blocks(block2, tom, block7), put_on_one_block(block2, tom, block4), grip_from_table(block5, tom), put_on_blocks(block5, tom, block2), grip_from_one_block(block7, tom, block6), put_on_table(block7, tom), grip_from_one_block(block1, tom, block3), put_on_one_block(block1, tom, block6), grip_from_table(block7, tom), put_on_blocks(block7, tom, block1), grip_from_table(block3, tom), put_on_blocks(block3, tom, block7)], _, _).

sequence_task(18, [grip_from_table(block6, tom), put_on_blocks(block6, tom, block1)], _, _).

sequence_task(17, [grip_from_blocks(block6, tom, block1), put_on_blocks(block6, tom, block2), grip_from_blocks(block1, tom, block5), put_on_table(block1, tom), grip_from_blocks(block6, tom, block2), put_on_blocks(block6, tom, block5), grip_from_one_block(block2, tom, block4), put_on_one_block(block2, tom, block1), grip_from_table(block4, tom), put_on_blocks(block4, tom, block6), grip_from_one_block(block2, tom, block1), put_on_table(block2, tom), grip_from_blocks(block4, tom, block6), put_on_one_block(block4, tom, block2), grip_from_blocks(block6, tom, block5), put_on_one_block(block6, tom, block1), grip_from_one_block(block4, tom, block2), put_on_blocks(block4, tom, block5), grip_from_table(block2, tom), put_on_blocks(block2, tom, block6), grip_from_blocks(block4, tom, block5), put_on_blocks(block4, tom, block2), grip_from_blocks(block5, tom, block7), put_on_table(block5, tom), grip_from_one_block(block7, tom, block3), put_on_table(block7, tom), grip_from_table(block5, tom), put_on_blocks(block5, tom, block4), grip_from_table(block7, tom), put_on_blocks(block7, tom, block5)], _, _).

sequence_task(16, [grip_from_blocks(block3, tom, block2), put_on_table(block3, tom), grip_from_blocks(block2, tom, block7), put_on_table(block2, tom), grip_from_blocks(block7, tom, block1), put_on_one_block(block7, tom, block2), grip_from_table(block3, tom), put_on_blocks(block3, tom, block1), grip_from_one_block(block7, tom, block2), put_on_blocks(block7, tom, block3), grip_from_table(block2, tom), put_on_blocks(block2, tom, block7)], _, _).

sequence_task(15, [grip_from_blocks(block6, tom, block4), put_on_table(block6, tom), grip_from_blocks(block4, tom, block5), put_on_blocks(block4, tom, block1), grip_from_table(block6, tom), put_on_blocks(block6, tom, block5), grip_from_blocks(block4, tom, block1), put_on_blocks(block4, tom, block6), grip_from_one_block(block1, tom, block2), put_on_blocks(block1, tom, block4), grip_from_table(block2, tom), put_on_blocks(block2, tom, block1)], _, _).

sequence_task(14, [grip_from_one_block(block4, tom, block3), put_on_one_block(block4, tom, block5), grip_from_one_block(block1, tom, block2), put_on_one_block(block1, tom, block6), grip_from_table(block7, tom), put_on_one_block(block7, tom, block2), grip_from_one_block(block4, tom, block5), put_on_table(block4, tom), grip_from_table(block5, tom), put_on_one_block(block5, tom, block3), grip_from_one_block(block7, tom, block2), put_on_blocks(block7, tom, block5), grip_from_one_block(block1, tom, block6), put_on_blocks(block1, tom, block7), grip_from_table(block2, tom), put_on_one_block(block2, tom, block4), grip_from_blocks(block1, tom, block7), put_on_table(block1, tom), grip_from_table(block6, tom), put_on_blocks(block6, tom, block7), grip_from_one_block(block2, tom, block4), put_on_blocks(block2, tom, block6), grip_from_table(block1, tom), put_on_blocks(block1, tom, block2), grip_from_table(block4, tom), put_on_blocks(block4, tom, block1)], _, _).

sequence_task(13, [grip_from_one_block(block7, tom, block3), put_on_blocks(block7, tom, block1), grip_from_table(block3, tom), put_on_blocks(block3, tom, block7), grip_from_blocks(block6, tom, block4), put_on_table(block6, tom), grip_from_blocks(block3, tom, block7), put_on_table(block3, tom), grip_from_table(block6, tom), put_on_blocks(block6, tom, block7), grip_from_one_block(block4, tom, block2), put_on_blocks(block4, tom, block6), grip_from_table(block3, tom), put_on_blocks(block3, tom, block4), grip_from_table(block2, tom), put_on_blocks(block2, tom, block3)], _, _).

sequence_task(12, [grip_from_one_block(block1, tom, block2), put_on_blocks(block1, tom, block4), grip_from_table(block2, tom), put_on_blocks(block2, tom, block1), grip_from_one_block(block7, tom, block3), put_on_blocks(block7, tom, block2), grip_from_table(block3, tom), put_on_blocks(block3, tom, block7)], _, _).

sequence_task(11, [grip_from_blocks(block1, tom, block2), put_on_blocks(block1, tom, block7), grip_from_one_block(block2, tom, block6), put_on_blocks(block2, tom, block1), grip_from_one_block(block5, tom, block4), put_on_blocks(block5, tom, block2), grip_from_table(block4, tom), put_on_blocks(block4, tom, block5), grip_from_table(block6, tom), put_on_blocks(block6, tom, block4)], _, _).

sequence_task(10, [grip_from_one_block(block5, tom, block2), put_on_blocks(block5, tom, block4), grip_from_table(block2, tom), put_on_blocks(block2, tom, block5), grip_from_table(block1, tom), put_on_blocks(block1, tom, block2)], _, _).

sequence_task(9, [grip_from_blocks(block6, tom, block3), put_on_blocks(block6, tom, block7), grip_from_blocks(block3, tom, block2), put_on_blocks(block3, tom, block6), grip_from_one_block(block2, tom, block1), put_on_table(block2, tom), grip_from_table(block1, tom), put_on_one_block(block1, tom, block2), grip_from_blocks(block3, tom, block6), put_on_table(block3, tom), grip_from_one_block(block1, tom, block2), put_on_one_block(block1, tom, block3), grip_from_table(block2, tom), put_on_blocks(block2, tom, block6), grip_from_one_block(block1, tom, block3), put_on_blocks(block1, tom, block2), grip_from_table(block3, tom), put_on_blocks(block3, tom, block1)], _, _).

sequence_task(8, [grip_from_table(block6, tom), put_on_blocks(block6, tom, block1), grip_from_one_block(block7, tom, block3), put_on_blocks(block7, tom, block6), grip_from_table(block3, tom), put_on_blocks(block3, tom, block7), grip_from_table(block5, tom), put_on_blocks(block5, tom, block3)], _, _).

sequence_task(7, [grip_from_blocks(block5, tom, block7), put_on_table(block5, tom), grip_from_one_block(block7, tom, block2), put_on_table(block7, tom), grip_from_table(block5, tom), put_on_blocks(block5, tom, block4), grip_from_table(block7, tom), put_on_one_block(block7, tom, block2)], _, _).

sequence_task(6, [grip_from_one_block(block4, tom, block3), put_on_blocks(block4, tom, block5), grip_from_one_block(block7, tom, block1), put_on_table(block7, tom), grip_from_table(block1, tom), put_on_blocks(block1, tom, block4), grip_from_table(block7, tom), put_on_one_block(block7, tom, block3), grip_from_blocks(block1, tom, block4), put_on_blocks(block1, tom, block7), grip_from_blocks(block4, tom, block5), put_on_blocks(block4, tom, block1), grip_from_blocks(block5, tom, block2), put_on_blocks(block5, tom, block4), grip_from_one_block(block2, tom, block6), put_on_blocks(block2, tom, block5), grip_from_table(block6, tom), put_on_blocks(block6, tom, block2)], _, _).

sequence_task(5, [grip_from_blocks(block5, tom, block2), put_on_blocks(block5, tom, block6), grip_from_one_block(block2, tom, block4), put_on_blocks(block2, tom, block5), grip_from_table(block4, tom), put_on_blocks(block4, tom, block2)], _, _).

sequence_task(4, [grip_from_blocks(block1, tom, block4), put_on_table(block1, tom), grip_from_one_block(block4, tom, block2), put_on_table(block4, tom), grip_from_table(block1, tom), put_on_one_block(block1, tom, block2), grip_from_one_block(block7, tom, block3), put_on_table(block7, tom), grip_from_table(block4, tom), put_on_one_block(block4, tom, block3), grip_from_one_block(block6, tom, block5), put_on_blocks(block6, tom, block1), grip_from_table(block7, tom), put_on_blocks(block7, tom, block4), grip_from_table(block5, tom), put_on_blocks(block5, tom, block6), grip_from_blocks(block7, tom, block4), put_on_table(block7, tom), grip_from_blocks(block5, tom, block6), put_on_one_block(block5, tom, block7), grip_from_one_block(block4, tom, block3), put_on_blocks(block4, tom, block6), grip_from_table(block3, tom), put_on_blocks(block3, tom, block4), grip_from_one_block(block5, tom, block7), put_on_blocks(block5, tom, block3), grip_from_table(block7, tom), put_on_blocks(block7, tom, block5)], _, _).

sequence_task(3, [grip_from_table(block5, tom), put_on_one_block(block5, tom, block4), grip_from_table(block1, tom), put_on_blocks(block1, tom, block2), grip_from_one_block(block5, tom, block4), put_on_blocks(block5, tom, block1), grip_from_table(block4, tom), put_on_blocks(block4, tom, block5)], _, _).

sequence_task(2, [grip_from_blocks(block3, tom, block7), put_on_table(block3, tom), grip_from_blocks(block7, tom, block2), put_on_one_block(block7, tom, block1), grip_from_one_block(block5, tom, block4), put_on_one_block(block5, tom, block3), grip_from_table(block4, tom), put_on_blocks(block4, tom, block7), grip_from_one_block(block5, tom, block3), put_on_blocks(block5, tom, block2), grip_from_blocks(block4, tom, block7), put_on_blocks(block4, tom, block5), grip_from_table(block3, tom), put_on_blocks(block3, tom, block7), grip_from_blocks(block4, tom, block5), put_on_blocks(block4, tom, block3), grip_from_blocks(block5, tom, block2), put_on_blocks(block5, tom, block4), grip_from_one_block(block2, tom, block6), put_on_table(block2, tom), grip_from_blocks(block5, tom, block4), put_on_one_block(block5, tom, block6), grip_from_blocks(block4, tom, block3), put_on_one_block(block4, tom, block2), grip_from_one_block(block5, tom, block6), put_on_table(block5, tom), grip_from_one_block(block4, tom, block2), put_on_blocks(block4, tom, block3), grip_from_table(block6, tom), put_on_one_block(block6, tom, block5)], _, _).

sequence_task(1, [grip_from_blocks(block5, tom, block2), put_on_table(block5, tom), grip_from_table(block7, tom), put_on_blocks(block7, tom, block2), grip_from_table(block5, tom), put_on_one_block(block5, tom, block3), grip_from_one_block(block4, tom, block6), put_on_blocks(block4, tom, block5), grip_from_blocks(block7, tom, block2), put_on_blocks(block7, tom, block4), grip_from_table(block6, tom), put_on_blocks(block6, tom, block2), grip_from_blocks(block7, tom, block4), put_on_blocks(block7, tom, block6), grip_from_blocks(block4, tom, block5), put_on_blocks(block4, tom, block7), grip_from_one_block(block5, tom, block3), put_on_blocks(block5, tom, block4), grip_from_table(block3, tom), put_on_blocks(block3, tom, block5)], _, _).

